source("R/core.R")
source("R/graph.R")
source("R/information.R")

n <- 8L
support <- assignments(n, n / 2)
y0 <- c(0, 0, 0, 0, 1, 1, 1, 1)
accepted <- c(2L, 1L, 3:8)
groups <- list(
  near = rep(1:4, each = 2),
  far = c(1, 1, 2, 3, 2, 4, 3, 4)
)
graphs <- lapply(groups, function(x) outer(x, x, "=="))
graphs <- c(list(rate_only = matrix(TRUE, n, n)), graphs)
rows <- list()
for (effect in c(0, 1, 2, 4)) {
  for (assignment_id in seq_len(nrow(support))) {
    z <- support[assignment_id, ]
    y <- y0 + effect * z
    oracle <- sharp_null_p(y, z, support)
    for (method in c("oracle", names(graphs))) {
      if (method == "oracle") {
        lower <- upper <- contrast(y, z)
        p <- oracle
      } else {
        fit <- graph_information_test(y, z, graphs[[method]], accepted, 2)
        lower <- fit$lower
        upper <- fit$upper
        p <- fit$p_value
      }
      rows[[length(rows) + 1L]] <- data.frame(
        effect, assignment_id, method, lower, upper, width = upper - lower,
        p_value = p, oracle_p = oracle, accepted_estimate = contrast(y[accepted], z),
        oracle_estimate = contrast(y, z), actual_accuracy = mean(accepted == seq_len(n))
      )
    }
  }
}
results <- do.call(rbind, rows)
summary_rows <- list()
for (effect in unique(results$effect)) {
  for (method in unique(results$method)) {
    part <- results[results$effect == effect & results$method == method, ]
    stopifnot(nrow(part) == choose(n, n / 2), all(part$p_value >= part$oracle_p - 1e-12))
    for (alpha in c(.05, .1, .2)) {
      summary_rows[[length(summary_rows) + 1L]] <- data.frame(
        effect, method, alpha, assignments = nrow(part), mean_width = mean(part$width),
        rejection_rate = mean(part$p_value <= alpha + 1e-12),
        oracle_estimate_containment = mean(
          part$lower <= part$oracle_estimate + 1e-12 &
            part$upper >= part$oracle_estimate - 1e-12
        )
      )
    }
  }
}
summary <- do.call(rbind, summary_rows)
null <- summary[summary$effect == 0, ]
stopifnot(all(null$rejection_rate <= null$alpha + 1e-12))

# A common observed dataset and accepted map isolate the graph's added information.
z <- c(rep(1, 4), rep(0, 4))
example <- do.call(rbind, lapply(names(graphs), function(method) {
  fit <- graph_information_test(z, z, graphs[[method]], accepted, 2)
  data.frame(method, lower = fit$lower, upper = fit$upper, p_value = fit$p_value)
}))
output <- "results/graph-information"
dir.create(output, recursive = TRUE, showWarnings = FALSE)
write.csv(results, file.path(output, "assignments.csv"), row.names = FALSE)
write.csv(summary, file.path(output, "summary.csv"), row.names = FALSE)
write.csv(example, file.path(output, "same-accuracy-example.csv"), row.names = FALSE)
writeLines(
  trimws(capture.output(sessionInfo()), which = "right"), file.path(output, "sessionInfo.txt")
)

lines <- c(
  "# Information retained by candidate graphs", "",
  "Generated by `make graph-information`. All 70 assignments are enumerated;",
  "these rejection probabilities have no Monte Carlo error. The 5% level is below.", "",
  "| Effect | Method | Mean estimate-range width | Rejection probability |",
  "|---:|:---|---:|---:|"
)
part <- summary[summary$alpha == .05, ]
lines <- c(lines, sprintf(
  "| %g | %s | %.4f | %.4f |", part$effect, part$method, part$mean_width, part$rejection_rate
), "",
"Effect zero reports exact Fisher sharp-null size; positive effects report power.",
"Widths describe reconstructed estimates, not confidence intervals. The oracle",
"has zero linkage width while still facing randomization uncertainty.", "",
"Every method has the same accepted permutation (two errors), true identity map,",
"and eight units. Rate-only retains full donor conservation plus an at-most-two",
"identity-error budget. Near and far add different fixed pair candidate graphs;",
"both have two candidates per record and contain all true edges. These are",
"controlled information sets, not estimated or empirically calibrated graphs.", "",
"The small design is discrete: a larger effect need not raise power at every step.",
"The full summary includes 10% and 20% thresholds. The assignment-level file",
"preserves every result, including failures to reject. No assignment is dropped.", "",
"See [formalization and proofs](../../research/graph-information.md).")
writeLines(lines, file.path(output, "report.md"))
print(summary[summary$alpha == .05, ], row.names = FALSE)
